cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<pizza_slug>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<pizza_slug>\d+)/$', views.cart_remove, name='cart_remove'),
]

pizza/urls.py
from django.urls import path

from pizza import views

urlpatterns = [
    path('', views.ListPizza.as_view(), name='index'),
    path('add/', views.AddPost.as_view(), name='add_pizza'),
    path('<slug:slug>/', views.ViewPizza.as_view(), name='pizza')
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, FormView
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django import forms
# from django.db import models


# class PizzaUser(models.Model, User):
#     user = models.OneToOneField(User)
#     number = models.IntegerField(max_length=12, blank=True)
#     address = models.CharField(max_length=100, blank=True)


class PizzaUserCreationForm(UserCreationForm):

    class Meta:
        model = User

        fields = ('username', 'first_name', 'email')
        field_classes = {
            'username': UsernameField
        }
        widgets = {
            'email': forms.EmailInput(attrs={'required': 'required'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class RegisterUser(FormView):
    form_class = PizzaUserCreationForm
    template_name = 'registration/register.html'
    success_url = '/login/'

    def form_valid(self, form):
        form.save()

        return super().form_valid(form)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls'), name='cart'),
    path('', TemplateView.as_view(template_name='index.html')),
    path('pizza/', include('pizza.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', RegisterUser.as_view(), name='register')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

pizza/models.py
from django.db import models
from django.utils.text import slugify
from time import time
from django.shortcuts import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


class PizzaPost(models.Model):
    title = models.CharField(max_length=32, db_index=True)
    price = models.FloatField()
    image = models.ImageField(default=None)
    description = models.TextField(default=None)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title) + str(int(time()))

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pizza', kwargs={'slug': self.slug})

#    @login_required()
#    def add_pizza_to_order(self):
#        ShoppingCartModel.user = user.id
#        ShoppingCartModel.id_pizzas[self.title] = self.price
#
#        return


class ShoppingCartModel(models.Model):
    order_id = models.CharField(max_length=50, auto_created=True)
    order_time = models.DateTimeField(auto_now_add=True)
    count = models.IntegerField(default=1)
    pizza_slug = models.SlugField()
    kind_of_pizza = models.ForeignKey(PizzaPost, unique=False, on_delete=models.CASCADE)

    class Meta:
        ordering = ['order_time']

    def total(self):
        return self.count * self.kind_of_pizza.price

    def name(self):
        return self.kind_of_pizza.title

    def price(self):
        return self.kind_of_pizza.price

    def augment_count(self, count):
        self.count += self.count
        self.save()





#    address = models.TextField(max_length=128, default=None, db_index=True)
#    number = models.IntegerField(default=0)
#    user = models.CharField(max_length=150)
#    full_price = models.FloatField()
#    id_pizzas = {}
#
#    template = 'pizza/shopping_cart.html'
#
#    def __str__(self):
#        return self.user

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
#    quantity = forms.IntegerField(min_value=1, max_value=20)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

pizza/forms.py
from django import forms

from pizza.models import PizzaPost, ShoppingCartModel


class PizzaForm(forms.ModelForm):
    class Meta:
        model = PizzaPost
        fields = ['title', 'price', 'image', 'description']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control-file'})
        }


class ShoppingCartForm(forms.ModelForm):
    class Meta:
        model = ShoppingCartModel
#        fields = ['address', 'number', 'user']
        fields = ['count', 'pizza_slug']

        widgets = {
            'count': forms.TextInput(attrs={'class': 'form-control'}),
        }

#        widgets = {
#            'address': forms.TextInput(attrs={'class': 'form-control'}),
#            'number': forms.TextInput(attrs={'class': 'form-control'})
#        }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(ShoppingCartForm, self).__init__(*args, **kwargs)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from pizza.models import PizzaPost
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, pizza_slug):
    cart = Cart(request)
    product = get_object_or_404(PizzaPost, id=pizza_slug)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=1,
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, pizza_slug):
    cart = Cart(request)
    product = get_object_or_404(PizzaPost, id=pizza_slug)
    print(product)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)

    return render(request, 'cart/detail.html', context={'cart': cart})

pizza/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View

from pizza.models import PizzaPost
from pizza.forms import PizzaForm, ShoppingCartModel
from cart.forms import CartAddProductForm


class ListPizza(View):
    model = PizzaPost
    order_object = ShoppingCartModel
    template = 'pizza/index.html'

    def get(self, request):
        objects = self.model.objects.all()

        return render(
            request,
            'pizza/index.html',
            context={
                'objects': objects
            }
        )

    def post(self, request):
        order = self.order_object
#        order = self.order_object.id_pizzas
#        'order': order

        return


class ViewPizza(View):
    template = 'pizza/pizza.html'

    def get(self, request, slug):
        pizza = get_object_or_404(PizzaPost, slug=slug)

        return render(
            request,
            self.template,
            context={
                'pizza': pizza
            }
        )


class AddPost(View):
    form_object = PizzaForm
    template = 'pizza/add_pizza.html'

    def get(self, request):
        form = self.form_object

        return render(
            request,
            self.template,
            context={
                'form': form
            }
        )

    def post(self, request):
        form = self.form_object(request.POST, request.FILES)
        if form.is_valid():
            object_form = form.save()
            return redirect(object_form)

        return render(
            request,
            self.template,
            context={
                'form': form
            }
        )


# class ShoppingCartView(View):
#     form_object = ShoppingCartForm


def product_detail(request, id, slug):
    product = get_object_or_404(PizzaPost,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    return render(request,
                  'pizza/pizza.html',
                  {'product': product,
                   'cart_product_form': cart_product_form}
                  )

cart/templates/cart/detail.html
{% extends "pizza/base.html" %}
{% load static %}
{% block title %}
    Shopping cart
{% endblock %}

{% block body %}
    <form class="text-center" action="{% url 'cart:cart_detail' %}" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <p class="text-centre">Ваш заказ:</p>
            {% for item in cart %}
                {% with pizza=item.product %}
                    <a href="{{ pizza.get_absolute_url }}">Название: {{ pizza }}</a>
                    <div>
                        <a>Количество: {{ item.quantity }}</a>
                    </div>
                    <form action="{% url "cart:cart_remove" item.product.id %}" method="post">
                        <div class="mx-auto" style="width: 200px;">
                            {% csrf_token %}
                            <input type="submit" value="Remove">
                        </div>
                    </form>
                    <p class="text-center">Цена: {{ item.total_price }}</p>
                {% endwith %}
            {% endfor %}
            <p class="text-center">Полная стоимость: {{ cart.get_total_price }}</p>

            {% csrf_token %}
            {% for field in form %}
                {{ field.label }}
                {{ field }}
            {% endfor %}
            <button type="submit" class="btn btn-success">Заказать</button>
        </div>
    </form>

{% endblock %}

pizza/templates/pizza/add_pizza.html
{% extends 'pizza/base.html' %}

{% block title %}
    Добавление новой пиццы
{% endblock %}

{% block body %}
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.errors }}
        </div>
    {% endif %}

    <form action="{% url 'add_pizza' %}" method="post" enctype="multipart/form-data">
        <div class="form-group">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label }}
                {{ field }}
            {% endfor %}
            <button type="submit" class="btn btn-success">Create</button>
        </div>
    </form>

{% endblock %}

pizza/templates/pizza/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            PizzaSite
        {% endblock %}
    </title>


    <!-- stylesheet -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>


</head>
<body>

{% include 'pizza/includes/Navbar.html' %}

<div class="body">
    {% block body %}

    {% endblock %}
</div>
</body>
</html>

pizza/templates/pizza/includes/Navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <a class="navbar-brand">Pizza-site</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}" methods="post">Главная страница<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">

                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}" methods="post">Корзина</a>
                {% else %}
                    <a class="nav-link" href="/login/">Корзина</a>
                {% endif %}

            </li>
            {% if  user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_pizza' %}">Добавить новую пиццу</a>
                </li>
            {% endif %}

        </ul>
        {% if user.is_authenticated %}
            <li class="nav-item">
                Hi, {{ user.username }}
            </li>
            <li class="nav-item">

                <a href="/logout/"> Log Out</a>
            </li>
        {% else %}
            <a href="/login/">Log In/Sign Up</a>
        {% endif %}
    </div>
</nav>

pizza/templates/pizza/includes/pizzas.html
{% load static %}
{% load image_filter %}

{% for pizza in objects %}
    <div class="shadow-lg p-3 mb-5 bg-white rounded">
        <a href="{{ pizza.get_absolute_url }}">
            <div class="col mb-4">
                <div class="card">
                    {% if pizza.image|is_exists %}
                        <img src="{{ pizza.image.url }}" class="card-img-top main-content" alt="...">
                    {% else %}
                        <img src="{% static 'pizza/image/pizza?.png' %}" class="card-img-top main-content" alt="...">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ pizza.title|title }}</h5>
                        <p class="card-text">{{ pizza.description|truncatechars:128 }}</p>
                    </div>
                    <div class="card-footer">
                        <p class="text-muted">Цена: {{ pizza.price|truncatechars:30 }}</p>
                    </div>

                    {% if user.is_authenticated %}
                        <form action="{% url "cart:cart_add" pizza.id %}" method="post">
                            {{ cart_product_form }}
                            {% csrf_token %}
                            <input type="submit" value="Добавить в корзину">
                        </form>
                    {% else %}
                        <a class="btn btn-primary btn-lg" href="/login/">Добавить в корзину</a>
                    {% endif %}
                </div>
            </div>
        </a>
    </div>
{% endfor %}

pizza/templates/pizza/index.html
{% extends 'pizza/base.html' %}

{% block body %}
    <div id="pizzas" class="row row-cols-1 row-cols-md-4">
        {% include 'pizza/includes/pizzas.html' %}
    </div>
{% endblock %}

pizza/templates/pizza/pizza.html
{% extends 'pizza/base.html' %}
{% load image_filter %}
{% load static %}


{% block title %}
    {{ pizza.title }}
{% endblock %}

{% block body %}
    <div class="card">
        {% if pizza.image|is_exists %}
            <img src="{{ pizza.image.url }}" class="card-img-top main-content" alt="...">
        {% else %}
            <img src="{% static 'pizza/image/pizza?.png' %}" class="card-img-top main-content" alt="...">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ pizza.title|title }}</h5>
            <p class="card-text">{{ pizza.description|truncatechars:128 }}</p>
        </div>
        <div class="card-footer">
            <p class="text-muted">Цена: {{ pizza.price|truncatechars:30 }}</p>
        </div>
    </div>
    {% if user.is_authenticated %}
        <form action="{% url "cart:cart_add" pizza.id %}" method="post">
            <div class="mx-auto" style="width: 200px;">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Добавить в корзину">
            </div>
        </form>
    {% else %}

        <div class="mx-auto" style="width: 200px;">
            <a class="btn btn-primary btn-lg" href="/login/">Добавить в корзину</a>
        </div>
    {% endif %}

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="0.2;url={% url 'index' %}">
    <title>PizzaSite</title>
    <style>
        img {
            height: 98vh;
            width: 100%;
        }
    </style>
</head>
<body>
    <div>
        <img src="https://www.intex-press.by/wp-content/uploads/2020/02/img4.goodfon.ru_.jpg">
    </div>
</body>
</html>